language: php

sudo: false
dist: trusty

git:
  depth: 3

notifications:
  email: false
  slack:
    secure: VRgYJteKWcJp+AgI8zjKStJ8YYS40OtocfuPH4Kbu/eWJrr9g3xLCdzn+b31iaM6pZtk2WfvXuADfoKsl8g/QLAyPoO+k8QxXmtpPFjiFrO3NnKywMORZbly4aOILKPZBJK3e9v1D7GyouL3/1g9wTr68v6AVFJbY339PGGwuHKc/5iUbtzfum9XTLLrBJmvStAP7l58/vX3aJrqUgKUGDf+TMwDuEX4ZKz/uXHPn0Yto0jZg8rUyYBhRGhXXkbmZO6lhVJ6kUgd3/7c3YrzLQHXy1nzzCljrO1pAOdl5hygmhJLia6GGUbphMBgCDryF/NH7qlp6BtFJTTA3nS3aYgaEInThQtDOlBojUqyC3ZJwmGCI7mWFj8nPcJPyHRto513lzU25K9lVdjfOXyH/+iBDIam6h+HcR++UtlhWbSTxtUqa0Izvc+1pJMfbWIYu1HPolz1kg4RTYttQIeJDQnLpEd5Y/j1QCc8alLfTnnKze1eB2coG9SLhtInZKsVe+Q3nPQuoKQF3aFz9z45C0lfgGF8FdHi2vqycmSDiKqxEbWfDiRgAAOXQNtuPSnGj6t3zStyytjuzQzvt2VaGcLL0Tpl7ryTi5kzEmzOPv9lBeOnhTF/BZdzFSRRUCWgwK4BpmTGClBskR825K4lJ21eXIaGNEIECWstRK49icI=

branches:
  only:
    - master
    - "/^v[0-9\\.]+/"

cache:
  yarn: true
  directories:
    - "${HOME}/.composer/cache"
    - node_modules

stages:
  - name: check
    if: branch = master and tag IS blank and type IN (pull_request, api, cron)

before_script:
  - git clone --depth=1 https://github.com/wp-content-framework/travis-ci.git travis-ci
  - bash travis-ci/bin/prepare.sh

jobs:
  fast_finish: true
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash travis-ci/bin/php/phpmd.sh
